name: Lint with Ruff

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
      TESTCONTAINER_DOCKER_NETWORK: cgn-ec-tests
      DOCKER_BUILDKIT: 1
      POSTGRES_HOST: localhost
      POSTGRES_USER: cgnec
      POSTGRES_PASSWORD: cgnec
      POSTGRES_DB: cgnec
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME="$HOME/.poetry" python - --yes
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Test Poetry installation
        run: poetry --version
      - name: Install dependencies
        run: |
          poetry install --no-interaction --with dev --all-extras
          poetry show --tree
      - name: Create Docker network for running Testcontainers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}
      - name: Run tests
        run: poetry run pytest tests/